FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY recommendation_system.py .
COPY Dataset/dataset_etudiants.csv .

CMD ["python", "recommendation_system.py"]