# Dockerfile.train
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copie du fichier requirements
COPY requirements.txt .

# Installation des dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copie de tout le code
COPY . .

# Commande à exécuter lors du build pour entraîner le modèle
CMD ["python", "knn.py"]
