version: '3.8'
services:
  api:
    image: mohamedalibouri/student-recommender-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./svd_student_model.pkl:/app/svd_student_model.pkl
      - ./svd_community_model.pkl:/app/svd_community_model.pkl
      - ./dataset_etudiants.csv:/app/dataset_etudiants.csv
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: mohamedalibouri/student-recommender-backend:latest
    ports:
      - "8501:8501"
    depends_on:
      - api