FROM python:3.9-slim

WORKDIR /app

# System updates and install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set pip timeout and retry flags
ENV PIP_DEFAULT_TIMEOUT=100
ENV PIP_RETRY=5
ENV PIP_TIMEOUT=300

# Install dependencies with increased timeout
COPY requirements-api.txt .
RUN pip install --no-cache-dir --timeout=100 --retries=5 -r requirements-api.txt

# Copy application code
COPY recommender.py .
COPY app.py .
COPY Dataset/dataset_etudiants.csv .

# Expose the port
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]