name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code à chaque push
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Créer un environnement virtuel
      - name: Create virtual environment
        run: python -m venv venv

      # Installer les dépendances
      - name: Install dependencies
        run: |
          . venv/bin/activate
          pip install -r requirements.txt
          
      # Ajouter le répertoire 'app' au PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV

      # Exécuter les tests
      - name: Run tests
        run: |
          . venv/bin/activate
          pytest app/tests/test_example.py
