name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérification du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Configurer l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Étape 3: Créer l'environnement virtuel
      - name: Create virtual environment
        run: python -m venv venv

      # Étape 4: Activer l'environnement et installer les dépendances
      - name: Install dependencies
        run: |
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 5: Ajouter 'app' au PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV

      # Étape 6: Vérification de la version de Python et des packages installés
      - name: Check Python version and installed packages
        run: |
          . venv/bin/activate
          python --version
          pip freeze

      # Étape 7: Exécuter les tests
      - name: Run tests
        run: |
          . venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q
