name: CI

on:
  push:
    branches:
      - eya-KNN  # Spécifier la branche 'eya-KNN'
  pull_request:
    branches:
      - eya-KNN  # Spécifier la branche 'eya-KNN'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: eya-KNN  # S'assurer que la branche 'eya-KNN' est check-out

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest app/tests/test_example.py
