name: Deploy FastAPI App

on:
  push:
    branches:
      - eya-KNN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/eya_knn_app .
          docker tag your-dockerhub-username/eya_knn_app your-dockerhub-username/eya_knn_app:latest
          docker push your-dockerhub-username/eya_knn_app:latest

      - name: Deploy container
        run: |
          docker run -d -p 8001:8001 --name eya_knn_app your-dockerhub-username/eya_knn_app
