name: Run tests

on:
  push:
    branches:
      - eya-KNN  # S'assurer que le pipeline ne s'exécute que pour la branche eya-KNN
  pull_request:
    branches:
      - eya-KNN  # S'assurer que le pipeline fonctionne pour les PR dans la branche eya-KNN

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Étape pour vérifier le code source
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape pour configurer Python avec la version souhaitée
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Utilise la version Python 3.9

    # Étape pour installer les dépendances nécessaires
    - name: Install dependencies
      run: |
        python -m venv venv  # Créer un environnement virtuel
        . venv/bin/activate  # Activer l'environnement virtuel
        pip install --upgrade pip  # Mettre à jour pip
        pip install -r requirements.txt  # Installer les dépendances du projet

    # Étape pour définir PYTHONPATH, qui permet de localiser les modules dans le répertoire app
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV  # Ajouter le répertoire app au PYTHONPATH

    # Étape pour exécuter les tests avec pytest
    - name: Run tests
      run: |
        . venv/bin/activate  # Activer l'environnement virtuel
        pip install pytest  # Assurer que pytest est installé dans l'environnement virtuel
        pytest --maxfail=1 --disable-warnings -q  # Exécuter pytest pour les tests, avec des options supplémentaires