name: CI Pipeline

on:
  push:
    branches:
      - eya-KNN  # La branche cible est maintenant 'eya-KNN'
  pull_request:
    branches:
      - eya-KNN  # La branche cible pour les PR est aussi 'eya-KNN'

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour les tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Récupère le code de ton dépôt GitHub

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Choisis la version de Python que tu utilises

      - name: Create virtual environment
        run: python -m venv venv  # Crée un environnement virtuel

      - name: Install dependencies
        run: |
          source venv/bin/activate  # Active l'environnement virtuel
          pip install -r requirements.txt  # Installe les dépendances définies dans requirements.txt

      - name: Install pytest
        run: |
          source venv/bin/activate  # Active l'environnement virtuel
          pip install pytest  # Installe pytest explicitement

      - name: Run tests
        run: |
          source venv/bin/activate  # Active l'environnement virtuel
          pytest app/tests/test_example.py  # Exécute tes tests avec pytest
