name: CI - Run Tests

on:
  push:
    branches:
      - eya-KNN  # Remplace par le nom de ta branche si besoin
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"  # Assure-toi que cette version correspond à ton projet

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Installation de pytest si non inclus dans requirements.txt

      - name: Run tests with pytest
        run: pytest  # Exécute tous les tests présents dans le projet

      - name: Linting with flake8 (optionnel)
        run: |
          pip install flake8
          flake8 app/ --max-line-length=88  # Vérifie si ton code suit les bonnes pratiques
