name: CI/CD Workflow for eya-KNN

# Déclencheur : ce workflow s'exécute uniquement pour la branche eya-KNN
on:
  push:
    branches:
      - eya-KNN
  pull_request:
    branches:
      - eya-KNN

jobs:
  build:
    runs-on: ubuntu-latest  # Ou windows-latest si tu veux exécuter sur Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Vérifie le code source

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Choisir la version de Python que tu utilises

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances à partir du fichier requirements.txt

    - name: Run tests
      run: |
        pytest  # Si tu utilises pytest pour tes tests
        # ou si tu veux tester manuellement un script:
        # python -m unittest discover tests  # Si tu utilises unittest pour les tests

    - name: Run application
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Lancer l'API pour vérifier si elle se lance correctement
